server.port: 8080
management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics, mappings, loggers, prometheus

springdoc:
  api-docs:
    enabled: true
    path: docs/v3/api-docs
  swagger-ui:
    enabled: true
    path: docs/swagger-ui.html

domain:
  update-movie-info:
    fixed-rate: 120
spring:
  application.name: MovieDb
  aop:
    proxy-target-class: true
  data:
    mongodb:
      uri: mongodb://movie_usr:test123@localhost:27017/movie_db
  cloud:
    openfeign:
      okhttp:
        enabled: true
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: full

adapter:
  client:
    omdb:
      url: http://www.omdbapi.com/
      # should be provided
      api-key: e4f33820

logging:
  level:
    root: INFO

dummy:
  users:
    - username: admin
      password: admin1
    - username: user
      password: test123
    - username: user2
      password: qwe123