version: '3.1'

services:
  mongo:
    image: mongo:latest
    container_name: movieDbContainer
    ports:
      - "27017:27017"
    volumes:
      - /Users/tasior/doceker/movie_db:/data/movie_db
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: movie_db
